using System.Globalization;
using System.Text;
using MelloRoos.Models;

namespace MelloRoos;

public static class SqlGenerator
{
    private const int MaxDescriptionLength = 250;

    public static string Generate(int debtId, List<EscalatedRateClass> rows, int landUseType = 0)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by MelloRoos rate extraction pipeline");
        sb.AppendLine($"-- debt_id={debtId}, rows={rows.Count}");
        sb.AppendLine();

        foreach (var row in rows)
            sb.AppendLine(GenerateInsert(debtId, row, landUseType));

        return sb.ToString();
    }

    private static string GenerateInsert(int debtId, EscalatedRateClass row, int landUseType)
    {
        var rc = row.RateClass;
        var description = Truncate(rc.ClassDescription ?? rc.ClassName, MaxDescriptionLength);
        var maxTaxText = FormatMaxTaxText(rc, row.CurrentMaxTaxRate);

        var columns = new[]
        {
            "debt_id", "display_order", "class_id", "class_name", "class_description", "class_other",
            "land_use", "land_use_type", "initial_roll_year", "max_tax_rate", "max_tax_unit",
            "max_tax_qty", "max_tax_qty_source", "current_roll_year", "current_max_tax_rate",
            "max_tax_text", "backup_tax_flag", "backup_tax_rate", "current_backup_tax_rate",
            "backup_tax_text", "rate_type"
        };

        var values = new[]
        {
            debtId.ToString(CultureInfo.InvariantCulture),
            rc.DisplayOrder.ToString(CultureInfo.InvariantCulture),
            rc.ClassId.ToString(CultureInfo.InvariantCulture),
            SqlString(rc.ClassName),
            SqlString(description),
            SqlNullableString(rc.ClassOther),
            SqlNullableString(rc.LandUse),
            landUseType.ToString(CultureInfo.InvariantCulture),
            row.InitialRollYear.ToString(CultureInfo.InvariantCulture),
            SqlNullableDecimal(rc.MaxTaxRate),
            SqlNullableString(rc.MaxTaxUnit),
            SqlNullableDecimal(rc.MaxTaxQty),
            SqlNullableString(rc.MaxTaxQtySource),
            row.CurrentRollYear.ToString(CultureInfo.InvariantCulture),
            SqlNullableDecimal(row.CurrentMaxTaxRate),
            SqlString(maxTaxText),
            rc.BackupTaxFlag ? "1" : "0",
            SqlNullableDecimal(rc.BackupTaxRate),
            SqlNullableDecimal(row.CurrentBackupTaxRate),
            SqlNullableString(rc.BackupTaxText),
            rc.RateType?.ToString(CultureInfo.InvariantCulture) ?? "NULL"
        };

        return $"INSERT INTO [dbo].[Rate] ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});";
    }

    private static string FormatMaxTaxText(RateClass rc, double? currentRate)
    {
        if (currentRate is null)
            return rc.ClassName;

        var amount = currentRate.Value.ToString("N2", CultureInfo.InvariantCulture);
        var unit = rc.MaxTaxUnit ?? "per unit";
        var desc = rc.ClassDescription;
        return desc is null or ""
            ? $"${amount} {unit} — {rc.ClassName}"
            : $"${amount} {unit} — {desc}";
    }

    private static string Truncate(string value, int maxLength)
    {
        if (value.Length <= maxLength)
            return value;
        return value[..(maxLength - 3)] + "...";
    }

    private static string SqlString(string value) => $"N'{value.Replace("'", "''")}'";

    private static string SqlNullableString(string? value) =>
        string.IsNullOrWhiteSpace(value) ? "NULL" : SqlString(value);

    private static string SqlNullableDecimal(double? value) =>
        value is null ? "NULL" : Math.Round(value.Value, 2, MidpointRounding.AwayFromZero).ToString(CultureInfo.InvariantCulture);
}
